#Test user-service

server:
  port: 0 # Ramdom port

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    # Eureka Server insert
    register-with-eureka: true
    # Eureka server instance info time to return
    fetch-registry: true
    # Eureka server location insert
    service-url:
      # endpoint
      defaultZone: http://127.0.0.1:9090/eureka