server:
  port: 0 # ?? ?? ??

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    # Eureka ?? ??
    register-with-eureka: true
    # Eureka ????? ???? ??? ????? ???? ??
    fetch-registry: true
    # Eureka ?? ?? ??
    service-url:
      # endpoint ??
      defaultZone: http://127.0.0.1:9090/eureka